### ISSUE TITLE
in-place editing

### ISSUE THREAD

**Issue by dyoder** [pandastrike/yaml-cli#2]
Ala `sed -i`

**Comment by joserobleda** [comment]
This one will be nice!

**Comment by smalot** [comment]
+1

**Comment by dyoder** [comment]
sorry i missed this PR.

thanks for the +1. i'll take a look at this soon.

**Comment by vivekmalhotragithub** [comment]
@dyoder are you still looking at PR? i am from 2021.

**Comment by dyoder** [comment]
Hi, sorry, I should have updated this ticket. I looked around at other similar projects and decided it wasn't worth continuing to develop this one. I recommend [yq](https://github.com/mikefarah/yq) instead.
