### ISSUE TITLE
cannot use yaml-cli with node:14-alpine docker image

### ISSUE THREAD

**Issue by vivekmalhotragithub** [pandastrike/yaml-cli#33]
basically i am trying to use your utility with node:14-alpine image in a k8s pod with my jenkins

this is my Dockerfile
```
FROM node:14-alpine

RUN apk update && apk add bash
RUN npm install -g yaml-cli@1.1.8

CMD ["yaml"]
```

when i use yaml command i am getting this error
```
(node:148) Warning: Accessing non-existent property 'producer' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by dyoder** [comment]
Hi,

I am no longer supporting this package (per the README), as there are other better modules available for this now. I recommend [yq](https://github.com/mikefarah/yq).

**Comment by vivekmalhotragithub** [comment]
thanks i actually already looked into yq and using it
